# Generated by Django 4.1.7 on 2023-05-17 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_enroll'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enroll',
            name='phone_number',
            field=models.CharField(max_length=10),
        ),
    ]
