# Generated by Django 4.1.7 on 2023-05-22 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_alter_enroll_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Demo',
            fields=[
                ('did', models.IntegerField(primary_key=True, serialize=False)),
                ('coursename', models.CharField(choices=[('PYTHON', 'Python'), ('DEVOPS', 'DevOps'), ('TESTING', 'Testing'), ('JAVA', 'Java'), ('POWERBI', 'PowerBI')], max_length=100)),
                ('faculty', models.CharField(max_length=20)),
                ('date_and_time', models.DateTimeField()),
                ('demotype', models.CharField(choices=[('ONLINE', 'Online'), ('OFFLINE', 'Offline'), ('ONLINE_OFFLINE', 'Online/Offline')], max_length=30)),
            ],
        ),
    ]
