# Generated by Django 4.1.7 on 2023-05-22 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_demo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='demo',
            name='date_and_time',
        ),
        migrations.AddField(
            model_name='demo',
            name='event_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='demo',
            name='event_time',
            field=models.TimeField(null=True),
        ),
    ]
