# Generated by Django 4.1.7 on 2023-05-24 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0006_remove_demo_date_and_time_demo_event_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemoAttend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StudentName', models.CharField(max_length=50)),
                ('Email', models.EmailField(max_length=40)),
                ('Mobile', models.CharField(max_length=10)),
                ('course', models.CharField(max_length=20, null=True)),
            ],
        ),
    ]
