# Generated by Django 4.1.7 on 2023-06-05 08:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crm', '0007_demoattend'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joining_date', models.DateField()),
                ('actual_fees', models.DecimalField(decimal_places=2, max_digits=8)),
                ('fees_paid', models.DecimalField(decimal_places=2, max_digits=8)),
                ('course', models.CharField(choices=[('Python', 'Python'), ('Python Full Stack', 'Python Full Stack'), ('DevOps', 'DevOps'), ('AWS', 'AWS'), ('MySQL', 'MySQL'), ('Java', 'Java'), ('Java Full Stack', 'Java Full Stack'), ('Testing', 'Testing')], max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
